// Package docs embeds the generated API contract and serves it.
//
// The OpenAPI document lives here rather than in a sibling directory because
// the go:embed directive cannot reach outside its own package. Keeping the
// generated file and the code that serves it together means the binary is
// self-contained — there is no runtime file to forget to ship — and there is
// exactly one copy of the spec, so it cannot drift from the proto.
package docs

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sync"

	"gopkg.in/yaml.v3"
)

// openAPIYAML is generated by `make generate` from proto/task/v1/task.proto and
// committed. CI regenerates and diffs it, so a change to the proto that is not
// reflected here fails the build.
//
//go:embed openapi.yaml
var openAPIYAML []byte

var (
	jsonOnce sync.Once
	jsonDoc  []byte
	jsonErr  error
)

// YAML returns the OpenAPI 3.1 document as generated.
func YAML() []byte { return openAPIYAML }

// JSON returns the same document as JSON, converted once on first use. Both
// spellings are served because tooling is split between them and converting on
// the fly is cheaper than committing two files that can disagree.
func JSON() ([]byte, error) {
	jsonOnce.Do(func() {
		var doc any
		if err := yaml.Unmarshal(openAPIYAML, &doc); err != nil {
			jsonErr = fmt.Errorf("parse embedded openapi.yaml: %w", err)
			return
		}
		jsonDoc, jsonErr = json.Marshal(doc)
	})
	return jsonDoc, jsonErr
}
